--- # Install the CCM

- name: Run the appliance installer to setup the CCM
  shell: /usr/lib/jvm/java-8-sun/bin/java -jar ccm-installer.jar ccm-response.xml > /tmp/logs/ccm-installer.log
  become: yes
  args:
    chdir: /tmp
  environment:
    JAVA_HOME: /usr/lib/jvm/java-8-sun

- name: Rebooting
  changed_when: "true"
  debug: msg='trigger machine reboot sequence'
  notify:
    - reboot sequence
  when: reboot? == true

- name: Configure Mail properties
  shell: "python config_mail_properties.py '{{ smtp_server }}' '{{smtp_user}}' '{{smtp_password}}' > /tmp/logs/config_mail.log"
  args:
    chdir: /tmp
  become: yes

- name: Configure Server properties
  shell: "python config_server_properties.py '{{ inventory_hostname }}' '{{ccm_public_url}}' '{{monitor_url}}' > /tmp/logs/config_server.log"
  args:
    chdir: /tmp
  become: yes

- name: Configure Management properties
  shell: "python config_mgmt_properties.py"
  args:
    chdir: /tmp
  become: yes
