--- # Install the CCM

- name: Run the appliance installer to setup the CCO
  shell: /usr/lib/jvm/java-8-sun/bin/java -jar cco-installer.jar cco-response.xml > /tmp/logs/cco_broker-response.log
  become: yes
  args:
    chdir: /tmp
  environment:
    JAVA_HOME: /usr/lib/jvm/java-8-sun

- name: Rebooting
  changed_when: "true"
  debug: msg='trigger machine reboot sequence'
  notify:
    - reboot sequence
  when: reboot? == true

- name: Configure Connection properties
  shell: "python config_conn_properties.py '{{ amqp_dns_name }}' '7788' '7789' > /tmp/logs/config_conn.log"
  args:
    chdir: /tmp
  become: yes

- name: Configure Gateway properties
  shell: "python config_gateway_properties.py '{{ monitor_id }}' '{{ ccm_hostname }}' > /tmp/logs/config_gateway.log"
  args:
    chdir: /tmp
  become: yes

- name: Configure Rabbit Server properties
  shell: "python config_rabbit_properties.py '{{ amqp_dns_name }}' '{{ cco_to_rabbit_port }}' > /tmp/logs/config_rabbit_server.log"
  args:
    chdir: /tmp
  become: yes
