--- # Download default installation files

- name: Create temp folders
  file:
    path: /tmp/logs
    state: directory

- name: Fetching installation files
  get_url:
    url: "{{ item.url }}"
    dest: "{{ item.dest }}"
    mode: 0755
  with_items:
    - url: "{{ core_installer_url }}"
      dest: /tmp/core_installer.bin
