---
# tasks file for cloud-center

- include: core_files.yml

- include: rabbit_files.yml
  when: component == 'rabbit'

- include: ccm_files.yml
  when: component == 'ccm'

- include: cco_files.yml
  when: component == 'cco'

- include: core_install.yml

- include: rabbit_install.yml
  when: component == 'rabbit'

- include: ccm_install.yml
  when: component == 'ccm'

- include: cco_install.yml
  when: component == 'cco'

- name: Rebooting
  changed_when: "true"
  debug: msg='trigger machine reboot sequence'
  notify:
    - reboot sequence
  when: reboot? == true
