---
# tasks file for cloud-center

- name: Setting hostname
  hostname:
    name: {{ hostname }}
  become: yes
  when: hostname != ''

- name: Rebooting
  changed_when: "true"
  debug: msg='trigger machine reboot sequence'
  notify:
    - reboot sequence
  when: reboot? == true


- include: core_files.yml

- include: rabbit_files.yml
  when: component == 'rabbit'

- include: ccm_files.yml
  when: component == 'ccm'

- include: cco_files.yml
  when: component == 'cco'

- include: core_install.yml
