--- # Download rabbit files

- name: Fetching Rabbit installation files
  get_url:
    url: "{{ item.url }}"
    dest: "{{ item.dest }}"
    mode: 0755
  with_items:
    - url: "{{ cco_installer_url }}"
      dest: /tmp/cco-installer.jar

- name: Copying conn_broker-response.xml
  template:
    src: ../templates/conn_broker-response.xml.j2
    dest: /tmp/conn_broker-response.xml

- name: Copying configuration scripts
  copy:
    src: "{{ item.src }}"
    dest: "{{ item.dest }}"
  with_items:
    - src: ./scripts/config_amqp_gateway_properties.py
      dest: /tmp/config_amqp_gateway_properties.py
    - src: ./scripts/config_gua_properties.py
      dest: /tmp/config_gua_properties.py
