---
# handlers file for cloudcenter

- name: reboot sequence
  changed_when: "true"
  debug: msg='trigger machine reboot sequence'
  notify:
    - get current time
    - reboot system
    - waiting for server to come back
    - verify a reboot was actually initiated

- name: get current time
  command: /bin/date +%s
  register: before_reboot

- name: reboot system
  shell: sleep 2 && shutdown -r now "Ansible package updates triggered"
  async: 1
  poll: 0
  ignore_errors: true
  become: yes

- name: waiting for server to come back
  local_action: wait_for host={{ inventory_hostname }} state=started delay=15 timeout=300

- name: verify a reboot was actually initiated
  # machine should have started after it has been rebooted
  shell: (( `date +%s` - `awk -F . '{print $1}' /proc/uptime` > {{ before_reboot.stdout }} ))
