--- # Install the CCM

- name: Update yum cache and upgrade packages
  yum:
    name: '*'
    state: latest
    update_cache: yes
    skip_broken: yes
  become: yes

- name: Install the CCO core packages
  shell: "/tmp/core_installer.bin {{os}} {{cloud_provider}} cco > /tmp/logs/core_installer.log"
  become: yes

- name: Run the appliance installer to setup the CCO
  shell: /usr/lib/jvm/java-8-sun/bin/java -jar cco-installer.jar cco-response.xml > /tmp/logs/cco_broker-response.log
  become: yes
  args:
    chdir: /tmp
  environment:
    JAVA_HOME: /usr/lib/jvm/java-8-sun
  notify:
    - reboot sequence

- name: Configure Connection properties
  shell: "python config_conn_properties.py '{{ amqp_dns_name }}' '7788' '7789' > /tmp/logs/config_conn.log"
  args:
    chdir: /tmp
  become: yes

- name: Configure Gateway properties
  shell: "python config_gateway_properties.py '{{ monitor_id }}' '{{ ccm_hostname }}' > /tmp/logs/config_gateway.log"
  args:
    chdir: /tmp
  become: yes

- name: Configure Rabbit Server properties
  shell: "python config_rabbit_properties.py '{{ amqp_dns_name }}' '5671' > /tmp/logs/config_rabbit_server.log"
  args:
    chdir: /tmp
  become: yes
  notify:
    - reboot sequence
